apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app: fe-finance-manage
  name: fe-finance-manage

  namespace: yjk-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fe-finance-manage
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fe-finance-manage
    spec:
      containers:
        - env:
            - name: DEBIAN_FRONTEND
              value: noninteractive
            - name: LANG
              value: C.UTF-8
            - name: DISPLAY
              value: ':99'
          image: '${IMAGE}'
          imagePullPolicy: Always
          name: fe-finance-manage
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: public-secret-acr
        - name: vpc-secret-acr
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime